core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', include("home.urls")),
    path('doc/', include("document.urls")),
    path('employee/', include("employee.urls")),
    path('notification/', include("notification.urls")),
    path('check-list/', include("check_list.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += i18n_patterns(path('__debug__/', include(debug_toolbar.urls)),)


handler404 = 'core.errors.custom_page_not_found_view'
handler500 = 'core.errors.custom_error_view'
handler403 = 'core.errors.custom_permission_denied_view'
handler400 = 'core.errors.custom_bad_request_view'

document/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create/', views.CreateDocView.as_view(), name="create_doc"),
    path('create/statement/', views.CreateStatementRaportView.as_view(), name="create_statement"),

    path('inbox/', views.InboxDocView.as_view(), name="inbox_doc"),
    path('statement/inbox/', views.InboxStatView.as_view(), name="inbox_stat"),
    path('statement/inbox/dir/', views.InboxDirStatView.as_view(), name="inbox_dir"),

    path('inbox/detail/<slug:slug>/', views.InboxDocumentDetailView.as_view(), name="detail-doc-view"),
    path('statement/detail/<slug:slug>/', views.StatementDetailView.as_view(), name="detail-stat-view"),
    path('director/detail/<slug:slug>/', views.DirectorStatementDetailView.as_view(), name="detail-ditector-view"),

    path('shipped/', views.ShippedDocumentView.as_view(), name="shipped_doc"),
    path('stats/shipped/', views.ShippedStatView.as_view(), name="shipped_stat"),
    path('shipped/detail/<slug:slug>/', views.ShippedDocumentDetailView.as_view(), name="detail-shipped-view"),

    path('inbox/remove/<slug:slug>/doc/', views.remove_inbox_doc, name="remove_inbox_doc"),
    path('inbox/remove/<slug:slug>/stat/', views.remove_inbox_stat, name="remove_inbox_stat"),
    path('inbox/remove/<slug:slug>/dir/', views.remove_inbox_stat_director, name="remove_inbox_director"),

    path('statement/detail/<slug:slug>/pdf/', views.RenderPDFStatement.as_view(), name="render-statement-pdf"),
]

document/models.py
import os

from django.db import models
from django.db.models.query_utils import select_related_descend
from django.forms import model_to_dict, widgets
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField

from .services import (
    STATUS, 
    STATUS_STATEMENT,
    REPLY_STATUS, 
    TYPE, PURPOSES, 
    APPOINTMENT, 
    create_notification,
    upload_to_reply_file, 
    upload_to_file, 
    create_number, 
    gen_slug
    )


class DocumentInProcessManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='In_process').order_by('-created')


class DocumentDoneManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='Done').order_by('-created')


class DocumentNotExecutedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='Not_completed').order_by('-created')


class MovementInProcessManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(document__status='In_process').order_by('-created')


class MovementDoneManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(document__status='Done').order_by('-created')


class MovementNotExecutedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(document__status='Not_completed').order_by('-created')


class Statement(models.Model):
    """Заявление и Рапорт"""
    number = models.CharField('Регистрационный номер', max_length=20, null=True, blank=True)
    author = models.ForeignKey('employee.Profile', verbose_name='Автор', on_delete=models.PROTECT, related_name='statements_author', null=True)
    type = models.CharField('Тип документа', max_length=20, choices=TYPE, default='Document')
    body = RichTextUploadingField('Описание документа')
    slug = models.SlugField(max_length=255, null=True, blank=True)
    status = models.CharField('Статус', max_length=20, choices=STATUS_STATEMENT, default='Submitted')
    director = models.ForeignKey('employee.Profile', verbose_name='Руководитель', on_delete=models.PROTECT, related_name='statements', null=True, blank=True)
    responsible = models.ForeignKey('employee.Profile', verbose_name='Ответственный', on_delete=models.PROTECT, related_name='statements_responsible', null=True, blank=True)

    is_editor_author = models.BooleanField(default=False)
    is_editor_director = models.BooleanField(default=True)
    is_editor_responsible = models.BooleanField(default=False)
    
    is_open_view_director = models.BooleanField(default=False)
    is_open_view_director_date = models.DateTimeField(null=True, blank=True)

    is_open_view_responsible = models.BooleanField(default=False)
    is_open_view_responsible_date = models.DateTimeField(null=True, blank=True)

    date_of_signing = models.DateTimeField(verbose_name='Дата подписания', blank=True, null=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()
        
    def save(self, *args, **kwargs):
        super(Statement, self).save(*args, **kwargs)
        self.number = create_number(self.pk)
        self.slug = gen_slug(self.number, self.author.get_full_name())
        if self.status == 'Done':
            self.is_editor_author = False
            self.is_editor_director = False
            self.is_editor_responsible = False
        super(Statement, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('detail-doc-view', kwargs={'slug': self.slug})

    def get_pdf_url(self):
        return reverse('render-statement-pdf', kwargs={'slug': self.slug})

    def status_v(self):
        return dict(STATUS_STATEMENT)[self.status]

    def type_v(self):
        return dict(TYPE)[self.type]

    def __str__(self):
        return f'{self.number}-{self.author}'

    class Meta:
        ordering = ('-created',)
        db_table = 'Statement'
        verbose_name = 'Заявление и Рапорт'
        verbose_name_plural = 'Заявлении и Рапорты'


class MessageStatement(models.Model):
    statement = models.ForeignKey(Statement, on_delete=models.CASCADE, related_name='messages')
    message = models.CharField(max_length=255)

    is_main = models.BooleanField(default=False)

    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.statement.author}-{self.message}'

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщении'


class Document(models.Model):
    """Документ"""
    number = models.CharField('Регистрационный номер', max_length=20, null=True, blank=True)
    author = models.ForeignKey('employee.Profile', verbose_name='Автор', on_delete=models.PROTECT, related_name='documents_author', null=True)
    name = models.CharField('Название документа', max_length=255)
    body = models.TextField('Описание документа')
    slug = models.SlugField()
    end_date = models.DateField(verbose_name='Срок исполнения', null=True, blank=True)
    purposes = models.CharField('Назначение', max_length=20, choices=PURPOSES, default='For_your_information')
    status = models.CharField('Статус', max_length=20, choices=STATUS, default='In_process')
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    objects = models.Manager()
    in_process = DocumentInProcessManager()
    done = DocumentDoneManager()
    not_executed = DocumentNotExecutedManager()
    
    def save(self, *args, **kwargs):
        super(Document, self).save(*args, **kwargs)
        self.number = create_number(self.pk)
        self.slug = gen_slug(self.number, self.name)[:40]
        super(Document, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('detail-shipped-view', kwargs={'slug': self.slug})

    def get_absolute_url_inbox(self):
        return reverse('detail-doc-view', kwargs={'slug': self.slug})

    def purposes_v(self):
        return dict(PURPOSES)[self.purposes]

    def status_v(self):
        return dict(STATUS)[self.status]

    def __str__(self):
        return f'{self.number}-{self.name}'

    class Meta:
        ordering = ('-created',)
        db_table = 'Document'
        verbose_name = 'Документ'
        verbose_name_plural = 'Документы'


class FileDocument(models.Model):
    document = models.ForeignKey(Document, on_delete=models.CASCADE, related_name='files')
    file = models.FileField('Файлы', upload_to=upload_to_file, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def filename(self):
        return os.path.basename(self.file.name)

    def __str__(self):
        return self.document.number

    class Meta:
        ordering = ('created',)
        verbose_name = 'Файл документа'
        verbose_name_plural = 'Файлы документов'


class MovementOfDocument(models.Model):
    """Движение документа"""
    document = models.ForeignKey(Document, on_delete=models.CASCADE, related_name='movements')
    responsible = models.ForeignKey('employee.Profile', on_delete=models.PROTECT, related_name='movements')
    status = models.CharField('Статус документа', max_length=20, choices=STATUS, default='In_process')
    is_main_person = models.BooleanField('Ответственный сотрудник', default=False)
    is_redirect = models.BooleanField('Перенаправлен сотруднику', default=False)
    is_send_reply = models.BooleanField('Можеть ли этот сотрудник отправить ответ', default=True)
    open_view = models.BooleanField(default=False)
    datetime_view = models.DateTimeField(verbose_name='Дата и время просмотра', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()
    in_process = MovementInProcessManager()
    done = MovementDoneManager()
    not_executed = MovementNotExecutedManager()

    def status_v(self):
        return dict(STATUS)[self.status]

    def __str__(self):
        return f'Движение: {self.document.number}-{self.responsible}'

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Движение документа'
        verbose_name_plural = 'Движения документов'


class ReplyDocument(models.Model):
    """Ответ на документ"""
    document = models.ForeignKey(Document, on_delete=models.CASCADE, related_name='answers', null=True)
    movement = models.ForeignKey(MovementOfDocument, on_delete=models.CASCADE, related_name='answers')
    appointment = models.CharField('Движение', choices=APPOINTMENT, max_length=30, default='Waiting')
    status = models.CharField('Статус ответа', max_length=20, choices=REPLY_STATUS, default='Waiting')
    description = models.TextField('Описание', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = models.Manager()

    def save(self, *args, **kwargs):
        if self.status == 'To_accept':
            self.movement.status = 'Done'
            self.movement.is_open_reply = False
            self.movement.save()
        super(ReplyDocument, self).save(*args, **kwargs)

    def status_v(self):
        return dict(STATUS)[self.status]

    def appointment_v(self):
        return dict(APPOINTMENT)[self.appointment]

    def __str__(self):
        return f'Ответ: {self.movement.document}'

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Ответ'
        verbose_name_plural = 'Ответы'


class FileReplyDocument(models.Model):
    movement = models.ForeignKey(MovementOfDocument, on_delete=models.CASCADE, related_name='answers_files', null=True)
    reply = models.ForeignKey(ReplyDocument, on_delete=models.CASCADE, related_name='files')

document/forms.py
from django.forms import ModelForm, Select, Textarea, TextInput, DateInput, FileInput
from django.utils import timezone

from ckeditor_uploader.fields import RichTextUploadingField
from .models import *
from datetime import timedelta


class BaseForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs['class'] = 'form-control'


class CreateDocumentForm(BaseForm):
    class Meta:
        model = Document
        fields = ['name', 'body', 'end_date', 'purposes']
        widgets = {
            'end_date': DateInput(attrs={'type': 'date', 'onload': 'validDate()', 'required': ''}),
        }


class CreateStatementRaportForm(BaseForm):
    class Meta:
        model = Statement
        fields = ['body']

templates/Document/Detail/base.html
{% extends 'Base/base.html' %}
{% load static %}

{% block title %}{{ movement.document.name }}{% endblock title %}

{% block content %}
<div class="row mt-3">
    <div class="col-lg-12 m-auto">
        <div class="card">
            <div class="card-body">
                <div class="card-title">
                    <span class='status mr-3'>
                        {% if movement.document.status == 'Done' %}
                            <i class="fa fa-circle mr-1" style="font-size: 20px; color: #16b81b"></i>
                        {% elif movement.document.status == 'Not_completed' %}
                            <i class="fa fa-circle mr-1" style="font-size: 20px; color: #bf4343"></i>
                        {% else %}
                            <i class="fa fa-circle mr-1" style="font-size: 20px; color: #daeb23"></i>
                        {% endif %}
                    </span>
                    <span class="author">{{ movement.document.author }}</span>
                    
                    <div class="card-action">
                         {{ movement.document.number }}
                    </div>
                </div>
                <hr>
                <ul class="nav nav-tabs nav-tabs-primary top-icon nav-justified">

                    <li class="nav-item">
                        <a href="javascript:void();" data-target="#document" data-toggle="pill" class="nav-link active"><i class="fa fa-file"></i> <span class="hidden-xs">Документ</span></a>
                    </li>

                    <li class="nav-item">
                        <a href="javascript:void();" data-target="#responsible" data-toggle="pill" class="nav-link"><i class="fa fa-group"></i> <span class="hidden-xs">Назначенные сотрудники</span></a>
                    </li>

                    <li class="nav-item">
                        <a href="javascript:void();" data-target="#reply" data-toggle="pill" class="nav-link"><i class="icon-note"></i> <span class="hidden-xs">Ответить</span></a>
                    </li>
                    
                </ul>

                <div class="tab-content pt-3 pb-0">

                    {% include 'Document/Detail/document.html' %}
                    
                    {% include 'Document/Detail/responsible.html' %}

                    {% include 'Document/Detail/reply.html' %}

                </div>
            </div>
        </div>
    </div>
</div>

<!--End Row-->
<script src="{% static 'js/multiselect.min.js' %}"></script>
<script>
	document.multiselect('#responsible')
		.setCheckBoxClick("checkboxAll", function(target, args) {
			console.log("Флажок Выбрать Все был нажат и получил значение ", args.checked);
		})
		.setCheckBoxClick("1", function(target, args) {
			console.log("Checkbox for item with value '1' was clicked and got value ", args.checked);
		});

</script>
{% endblock content %}

templates/Document/Detail/document.html
<div class="tab-pane active" id="document">
    <div class="row">
        <div class="col-lg-7 document_content">
            <h5 class="mb-4 mt-3">{{ movement.document.name }}</h5>
            <p class="text-justify" style="text-indent: 50px; margin-bottom: 90px;">
                {{ movement.document.body|safe  }}
            </p>

            <div class="footer_purposes" style='width: 97%;'>
                <hr>
                <div class="row">
                    <div class="col-lg-5">Назначение - {{ movement.document.purposes_v }}</div>
                    <div class="col-lg-7"><span class="float-right">Срок исполнения - {{ movement.document.end_date }}</span></div>
                </div>
            </div>            
        </div>

        <div class="col-lg-5">
            <h5 class="mb-4 mt-3"> Прикрепленные файлы <i class="ml-3 fa fa-paperclip"></i></h5>
            {% if files %}
                <ol>
                    {% for file in files %}
                        <li class="mb-3"> <i class="fa fa-file"></i> <a href="{{ file.file.url }}" download>{{ file.filename }}</a></li>
                    {% endfor %}
                </ol>
            {% else %}
                <p>Нет прикрепленного файла</p>
            {% endif %}
        </div>
        <div class="col-lg-12">
            <hr>
                <h6 class="mt-4 d-md-block d-none">Документ был отправлен - {{ movement.document.created }} <span class="float-right">Обновлено - {{ movement.document.updated }}</span></h6>
                <h6 class="mt-4 d-md-none d-block text-center">Отпр - {{ movement.document.created }} <br>Обно - {{ movement.document.updated }}</h6>
        </div>
    </div>
</div>

templates/Document/Detail/reply.html
<div class="tab-pane" id="reply">
    {% if movement.is_send_reply %}
        <form method="post" enctype="multipart/form-data"> {% csrf_token %}
            <div class="form-group reply_form_div m-auto text-center">
                <label class="col-form-label form-control-label">Ответить на письмо {{  movement.is_send_reply  }}</label>
                <div class="row">
                    <div class="col-lg-6 col-md-6 col-12 form-group">
                        <select class="form-control" name="appointment">
                            {% if user.is_admin and movement.document.purposes == 'For_approval' %}
                                <option value="I_approve">Утверждаю</option>
                            {% elif movement.document.purposes == 'For_agreement' %}
                                <option value="I_agree">Согласен</option>
                                <option value="I_dont_agree">Не согласен</option>
                            {% elif movement.document.purposes == 'To_be_executed' %}
                                <option value="Accepted_for_execution">Принято к исполнению</option>
                            {% elif movement.document.purposes == 'For_your_information' %}
                                <option value="Noted">Принято к сведенью</option>
                            {% endif %}
                        </select>
                    </div>
                    <div class="col-lg-6 col-md-6 col-12 form-group">
                        <input type="file" name="files" id="files" class="form-control" multiple="" accept=".txt, .webp, .jpg, .jpeg, .png, .docx, .doc, .pdf, .zip, .rar, .xlsx, .xlsm, .xlsb, .xls, .csv">
                    </div>
                    <div class="col-12 form-group">
                        <textarea name="body" cols="40" rows="10" class="form-control" required="" id="id_body"></textarea>
                    </div>
                </div>
                
                <div class="form-group">
                    <button type="submit" class="btn btn-light px-5 font-weight-bold" style="font-size: 18px"><i class="fa fa-paper-plane-o "></i> Отправить</button>
                </div>
            </div>
        </form>
        
    {% else %}
        <div class="row">
            <div class="col-lg-6 col-md-6 col-12 row m-auto">
                {% for answer in answers %}
                    <div class="card col-12">
                        <div class="card-body">
                            <div class="card-action" style='margin: 5px;'>
                                {% if answer.status == 'To_accept' %}
                                    <i class="fa fa-circle mr-1" style="font-size: 20px; color: #16b81b"></i>
                                {% elif answer.status == 'Not_accepted' %}
                                    <i class="fa fa-circle mr-1" style="font-size: 20px; color: #bf4343"></i>
                                {% else %}
                                    <i class="fa fa-circle mr-1" style="font-size: 20px; color: #daeb23"></i>
                                {% endif %}
                            </div>
                            <div class="card-title mb-3"><h4>{{ answer.movement.responsible }}</h4></div>
                            
                            <div class="row">
                                <div class="col-lg-8 col-md-8 col-12 answer_content">
                                    <h6>Ответ - {{ answer.appointment_v }} </h6>
                                    <p style='margin-bottom: 63px;'>{{ answer.description }}</p>
                                    <div class="footer_purposes" style='width: 95%;'>
                                        <hr>
                                        <p>Отправлен - {{ answer.created }}</p>
                                    </div>
                                </div>
                                <div class="col-lg-4 col-md-4 col-12">
                                    <h6 class=""> Прикрепленные файлы <i class="fa fa-paperclip"></i></h6>
                                    {% for file in answers_files %}
                                        {% if file.reply == answer %}
                                            <p class="mb-3">- <a href="{{ file.file.url }}" download style="font-size: 12px">{{ file.filename }}</a></p>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>

                            
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    {% endif %}
</div>

templates/Document/Detail/responsible.html
<div class="tab-pane" id="responsible">
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <tr>
                <th scope="col">Ф.И.О</th>
                <th scope="col">Просмотр</th>
                <th scope="col">Движение</th>
                <th scope="col">Дата</th>
            </tr>
            <tbody>
                {% for movement in movements %}
                    <tr>
                        <td>
                            {% if movement.is_main_person %}
                                <i class="fa fa-user mr-2"></i>
                            {% endif %}
                            {{ movement.responsible }}
                        </td>
                        <td>{% if movement.open_view %}Просмотрено{% else %}Не просмотрено{% endif %}</td>
                        <td>{{ movement.status_v }}</td>
                        <td>
                            {% if movement.status == 'In_process' %}
                                ---------
                            {% else %}
                                {{ movement.updated }}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>